//store all meals data here and can be update and imported
export const mealsStockData = [
  {
    id: "1",
    title: "House Cheese Curds",
    desc: "Lightly battered and fried and served with T.J. house sauce.",
    price: 13.0,
    img: "/img/meals/cheese_curds.jpg",
  },
  {
    id: "2",
    title: "The Bone-in Wings",
    desc: "Offers Boneless option as well.",
    price: 12.0,
    img: "/img/meals/wings.jpg",
  },
  {
    id: "3",
    title: "Chips and Queso",
    desc: "Fresh fried corn tortillas and queso topped with pico and Jalapenos.",
    price: 9.0,
    img: "/img/meals/chip_queso.jpg",
  },
  {
    id: "4",
    title: "Chicken Salad",
    desc: "Grilled chicken on mixed greens, crumbled Bleu cheese, diced cucumber, diced tomatoes, with balsamic glaze and cilantro lime dressing.",
    price: 15.0,
    img: "/img/meals/caesar_salad.jpg",
  },
  {
    id: "5",
    title: "House Onion Rings",
    desc: "Served with T.J. house sauce.",
    price: 12.0,
    img: "/img/meals/onion_ring.jpg",
  },
  {
    id: "6",
    title: "Buffalo Shrimp",
    desc: "Hand-breaded shrimp tossed in your favorite buffalo sauce.",
    price: 15.0,
    img: "/img/meals/buffalo_shrimp.jpg",
  },
  {
    id: "7",
    title: "Georgia Burger",
    desc: "House-made cracked peppered pulled pork, cheddar cheese, bbq sauce, onion straws, shredded lettuce, and mayo served on a toasted bun.",
    price: 17.0,
    img: "/img/meals/georgia_burger.jpg",
  },
  {
    id: "8",
    title: "Buffalo Chicken Wrap",
    desc: "Crispy buffalo chicken layered with lettuce, pico de gallo and Monterey Jack and Cheddar cheese in a grilled flour tortilla with a side of ranch or Bleu cheese dressing.",
    price: 14.0,
    img: "/img/meals/buffalo_chicken_wrap.jpg",
  },
  {
    id: "9",
    title: "The Handyman",
    desc: "Double smoked bacon, Wisconsin Cheddar, and Provolone, with lettuce, ketchup, mayo, sautéed onions, and pickles served on a toasted bun.",
    price: 15.0,
    img: "/img/meals/handyman.jpg",
  },
  {
    id: "10",
    title: "Turkey Bacon Club",
    desc: "On a ciabatta bun with lettuce-tomato and mayo.",
    price: 15.0,
    img: "/img/meals/turkey_bacon_club.jpg",
  },
  {
    id: "11",
    title: "The Bella Blue",
    desc: "Double smoked bacon, Wisconsin Bleu cheese, pickled red onions, balsamic mayo and shredded lettuce served on a toasted bun.",
    price: 17.0,
    img: "/img/meals/bella_blue.jpg",
  },
  {
    id: "12",
    title: "St Louis Style Ribs",
    desc: "Served with soup or salad, roll and choice of shoestring fries, coleslaw, mashed potatoes and gravy, or baked potato.",
    price: 21.0,
    img: "/img/meals/ribs.jpg",
  },
  {
    id: "13",
    title: "Broasted 1/2 Chicken",
    desc: "Served with coleslaw and a dinner roll and your choice of shoestring fries, tater tots or mashed potatoes and gravy.",
    price: 17.0,
    img: "/img/meals/roast_chicken.jpg",
  },
  {
    id: "14",
    title: "Chicken Alfredo",
    desc: "Penne pasta tossed in our house made cream sauce.",
    price: 14.0,
    img: "/img/meals/chicken_alfredo.jpg",
  },
  {
    id: "15",
    title: "Mostaccioli Pasta",
    desc: "Scratched made marinara sauce, Italian sausage, ground Angus beef, mozzarella cheese, parmesan cheese, parsley and garlic toast.",
    price: 13.0,
    img: "/img/meals/pasta.jpg",
  },
];
